[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "TIL"
  pageRef = "til"
  weight = 20

[[main]]
  name = "About"
  pageRef = "topics"
  weight = 30

[[main]]
  name = "Uses"
  pageRef = "uses"
  weight = 40

[[main]]
  name = "Me"
  parent = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Publications"
  parent = "About"
  pageRef = "publications"
  weight = 20

[[main]]
  name = "Talks"
  parent = "About"
  pageRef = "talks"
  weight = 30
