[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Learnings"
  pageRef = "til"
  weight = 20

[[main]]
  name = "Now"
  pageRef = "now"
  weight = 30

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 40

[[main]]
  name = "Uses"
  pageRef = "uses"
  weight = 50

[[main]]
  name = "About"
  pageRef = "topics"
  weight = 60

[[main]]
  name = "Me"
  parent = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Publications"
  parent = "About"
  pageRef = "publications"
  weight = 20

[[main]]
  name = "Talks"
  parent = "About"
  pageRef = "talks"
  weight = 30
